# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Guia AMI 2025
author: Analisis Matematico I
logo: logo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: guias.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/amipy25/guias
  path_to_book: /
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  extra_files:
    - ./img/

# MathJax and Sphinx settings
sphinx:
  extra_extensions:
    - sphinx.ext.mathjax
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        inlineMath: [["$", "$"], ["\\(", "\\)"]]
        displayMath: [["$$", "$$"], ["\\[", "\\]"]]
